# Generated by Django 4.1 on 2022-08-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_author_book_author1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author1',
            new_name='author',
        ),
    ]
